import Head from "next/head";
import Download from "../components/Download";
import Features from "../components/Features";
import Footer from "../components/Footer";
import Header from "../components/Header";
import Hero from "../components/Hero";
import Partners from "../components/Partners";
import Specs from "../components/Specs";

export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className="font-bai-jamjuree">
                <Header />
                <Hero />
                <Features />
                <Specs />
                <Partners />
                <Download />
            </main>
            <Footer />
        </>
    );
}
